version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/airData
      - IQ_AIR_API_URL=http://api.airvisual.com/v2/nearest_city
      - NEAREST_CITY_QUERY=?lat={{LATITUDE}}&lon={{LONGITUDE}}&key={{API_KEY}}
      - API_KEY=24cb85de-3d94-4207-934d-05734ecb4454

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
